import type { NextPage } from 'next'
import Head from 'next/head'
import { GetStaticProps } from 'next'
import { useState } from 'react'
import TableCoins from '../components/TableCoins'
import NavBar from '../components/NavBar'
import Todaysdate from '../components/Todaysdate'

export interface Coin {
  name: String,
  symbol: String,
  image: String,
  current_price: Number,
}

export interface PageProps {
  coins: Coin[]
  search: String | undefined
}

const Home = ( {coins}: PageProps ) => {

  const [search, setSearch]=useState<String|undefined>("")
  
  return (
    <div>
      <Head>
        <title>Crypto Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Todaysdate />
      <main >
      <div className="max-w-md mx-auto py-12">
        <input type="text" placeholder="Search a coin"
        onChange={ e => setSearch(e.target.value)}
        className="shadow border-0 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline 
        text-center text-xl font-semibold" />
        </div>
       <TableCoins coins={coins} search={search} />
      </main>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=eur&order=market_cap_desc&per_page=100&page=1&sparkline=false')
  const coins = await res.json()

  return {
    props: { coins, 
    },
  }
}
